service:
  name: hr-frontend
  port: 80
  containerPort: 3000

image:
  repository: acr.example.azurecr.io/hr-frontend
  tag: "1.0.0"

replicaCount: 2

ingress:
  enabled: true
  className: nginx
  host: hr.example.com
  path: /
  pathType: Prefix

env:
  NODE_ENV: production
